spring.application.name=cinema

#Database resource
spring.profiles.active=local

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql = true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.type.descriptor.sql.BasicBinder = TRACE

application.security.jwt.secret-key = 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration = 900000
application.security.jwt.refresh-token.expiration = 604800000
